name: backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths: ["server/**"]

jobs:
  QA:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: directory checkout
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2.5.1
        with:
          cache: "yarn"
          cache-dependency-path: server/yarn.lock
      - name: linting
        run: |
          yarn
          yarn lint
      - name: test build
        run: yarn build

  Build-n-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy backend to heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ci-cd-back"
          heroku_email: ${{secrets.MY_MAIL}}
          appdir: "server"
