name: docker image push
on:
  push:
    branches: [ main ]
jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: directory checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build docker image and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./server/
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/cicdfunserver:latest
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}