name: frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths: ["web/**"]

jobs:
  Node-Setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: directory checkout
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2.5.1
        with:
          cache: "yarn"
          cache-dependency-path: web/yarn.lock

      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: installing dependencies
        run: yarn --verbose --json > yarn-report.json

      - name: upload instalation report
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./web/yarn-report.json
          if-no-files-found: error

  Linting:
    needs: Node-Setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: directory checkout
        uses: actions/checkout@v2

      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: linting js
        run: |
          yarn
          yarn lint:js

      - name: linting css
        run: yarn lint:css

  Test-Build:
    needs: Node-Setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: directory checkout
        uses: actions/checkout@v2

      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: test build
        run: |
          yarn
          yarn build

  Unit-Tests:
    needs: Node-Setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: directory checkout
        uses: actions/checkout@v2

      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: unit testing
        run: |
          yarn
          yarn test --verbose --json > unit-test-report.json

      - name: upload testing report
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./web/unit-test-report.json
          if-no-files-found: error

  Dependency-Audit:
    needs: Node-Setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: directory checkout
        uses: actions/checkout@v2

      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: audit
        run: |
          yarn
          yarn yarn-audit-ci --high > audit-report.txt

      - name: upload audit report
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./web/audit-report.txt

  E2E-Tests:
    needs: Node-Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          browser: chrome
          headless: true

  Build-n-deploy-frontend:
    needs: [Linting, Test-Build, Unit-Tests, Dependency-Audit]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy frontend to heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ci-cd-front"
          heroku_email: ${{secrets.MY_MAIL}}
          appdir: "web"

  Failure-Report:
    if: failure()
    needs:
      [
        Linting,
        Test-Build,
        Unit-Tests,
        Dependency-Audit,
        Node-Setup,
        Build-n-deploy-frontend,
      ]
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: reports
      - run: cat ./**/reports
