name: frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths: ["web/**"]

jobs:
  Build-n-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy frontend to heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ci-cd-front"
          heroku_email: ${{secrets.MY_MAIL}}
          appdir: "web"
