name: frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths: ["web/**"]

jobs:
  QA:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn

      - name: linting
        uses: actions/setup-node@v2
      - run: yarn lint:js

  Build-n-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy frontend to heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ci-cd-front"
          heroku_email: ${{secrets.MY_MAIL}}
          appdir: "web"
